# Cloud Build for Lightweight Pipeline Service
# Run from: anime_dance_social_media/
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pipeline-char-to-vids:latest'
      - '-f'
      - 'cloud_run_pipeline_char_to_vids/Dockerfile'
      - '.'
    timeout: 900s  # 15 minutes
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pipeline-char-to-vids:latest'
  
  # Deploy to Cloud Run (scale-to-0 optimized)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pipeline-char-to-vids'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pipeline-char-to-vids:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--set-env-vars'
      - 'PIPELINE_API_KEY=aura-pipeline-2026-secret,GCP_PROJECT_ID=$PROJECT_ID,GCS_BUCKET_NAME=$PROJECT_ID'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/pipeline-char-to-vids:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
