"""
Cloud Migration Report Generator
Queries GCS and Firestore and generates a Markdown report.
"""
import sys
import os
from pathlib import Path

# Add project root to path
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from services.gcs_service import GCSService
from services.firestore_service import FirestoreService

def generate_report():
    report_path = ROOT / "CLOUD_MIGRATION_REPORT.md"
    
    gcs = GCSService()
    fs = FirestoreService()
    
    # GCS Data
    dance_files = gcs.list_files(prefix="anime_dance/dances/")
    dance_videos = [f for f in dance_files if f.endswith(".mp4")]
    dance_images = [f for f in dance_files if f.endswith(".png")]
    char_files = gcs.list_files(prefix="anime_dance/characters/")
    remix_files = gcs.list_files(prefix="anime_dance/remixes/")
    total_files = len(gcs.list_files())
    
    # Firestore Data
    char_count = fs.get_character_count()
    all_chars = fs.get_all_characters()
    
    total_assets = 0
    chars_with_dances = 0
    dance_count_total = 0
    gcs_uri_count = 0
    local_path_count = 0
    
    local_paths_examples = []
    
    for char in all_chars:
        assets = char.get("assets", [])
        total_assets += len(assets)
        char_has_dance = False
        for asset in assets:
            # Check for dance
            dance = asset.get("dance_video") or asset.get("primary_dance_video") or asset.get("DELIVERABLE")
            if dance:
                dance_count_total += 1
                char_has_dance = True
                
            # Check for GCS vs Local paths
            for key in ["anime_image", "cosplay_image", "dance_video", "primary_dance_video", "DELIVERABLE"]:
                val = asset.get(key)
                if val:
                    if str(val).startswith("gs://"):
                        gcs_uri_count += 1
                    else:
                        local_path_count += 1
                        if len(local_paths_examples) < 10:
                            local_paths_examples.append(f"{char.get('name')} - {key}: {val}")
        
        if char_has_dance:
            chars_with_dances += 1

    # Local Files Check
    local_dances_dir = ROOT / "output" / "dances"
    local_dance_videos_count = 0
    if local_dances_dir.exists():
        local_dance_videos_count = len([f for f in local_dances_dir.iterdir() if f.suffix == ".mp4"])

    # Generate Markdown
    md = f"""# ☁️ Cloud Migration Status Report
Generated on: {os.popen('date /t').read().strip()} {os.popen('time /t').read().strip()}

## 📊 Overall Summary
| Metric | Status |
| :--- | :--- |
| **GCS Sync Status** | {"✅ Complete" if local_dance_videos_count <= len(dance_videos) else "⚠️ In Progress"} |
| **Firestore Sync Status** | {"✅ Migrated" if local_path_count == 0 else "❌ local paths remain"} |
| **Migration Percent** | {int(gcs_uri_count / (gcs_uri_count + local_path_count) * 100) if (gcs_uri_count + local_path_count) > 0 else 0}% |

## 📦 Google Cloud Storage (GCS)
- **Bucket:** `{gcs.BUCKET_NAME}`
- **Total Files:** `{total_files}`
- **Dance Videos (.mp4):** `{len(dance_videos)}`
- **Dance Thumbnails/Images:** `{len(dance_images)}`
- **Character Assets:** `{len(char_files)}`
- **Remix Files:** `{len(remix_files)}`
- **Local Dance Videos:** `{local_dance_videos_count}` (Comparison)

## 🔥 Firestore Database
- **Collection:** `characters`
- **Total Characters:** `{char_count}`
- **Total Assets Count:** `{total_assets}`
- **Characters w/ Dances:** `{chars_with_dances}`
- **Total Dance Entries:** `{dance_count_total}`

## 🔗 Path Verification
- **GCS URIs (`gs://`):** `{gcs_uri_count}`
- **Local Paths:** `{local_path_count}`

{"### ⚠️ Detected Local Paths (Need Migration)" if local_paths_examples else ""}
{chr(10).join([f"- {ex}" for ex in local_paths_examples]) if local_paths_examples else ""}

---
*Report generated by Antigravity Cloud Auditor*
"""
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(md)
    
    print(f"✅ Report generated at: {report_path}")
    return report_path

if __name__ == "__main__":
    generate_report()
